#!/bin/bash -ex

dl() {
    [ "$FAB_HTTP_PROXY" ] && PROXY="--proxy $FAB_HTTP_PROXY"
    cd $2; curl -L -f -O $PROXY $1; cd -
}

SRC="/usr/local/src"
PLUGINS_SRC="/usr/local/src/wp-plugins"

# wordpress installation
dl http://wordpress.org/latest.tar.gz $SRC

# wordpress plugins (see http://www.turnkeylinux.org/wordpress)
mkdir -p $PLUGINS_SRC
URL="http://downloads.wordpress.org/plugin"
dl $URL/wordpress-seo.latest-stable.zip $PLUGINS_SRC
dl $URL/nextgen-gallery.zip $PLUGINS_SRC
dl $URL/stats.zip $PLUGINS_SRC
dl $URL/vipers-video-quicktags.zip $PLUGINS_SRC
dl $URL/google-analytics-for-wordpress.latest-stable.zip $PLUGINS_SRC
dl $URL/wp-polls.zip $PLUGINS_SRC
dl $URL/ozh-admin-drop-down-menu.zip $PLUGINS_SRC
dl $URL/wp-super-cache.1.2.zip $PLUGINS_SRC
dl $URL/sociable.4.3.3.zip $PLUGINS_SRC
dl $URL/simple-tags.2.2.zip $PLUGINS_SRC
dl $URL/wp-db-backup.2.2.3.zip $PLUGINS_SRC
dl $URL/podpress.8.8.10.13.zip $PLUGINS_SRC
dl $URL/wp-pagenavi.2.83.zip $PLUGINS_SRC
dl $URL/contact-form-7.3.3.3.zip $PLUGINS_SRC

