#!/bin/bash -ex

dl() {
    [ "$FAB_HTTP_PROXY" ] && PROXY="--proxy $FAB_HTTP_PROXY"
    cd $2; curl -L -f -O $PROXY $1; cd -
}

SRC="/usr/local/src"
PLUGINS_SRC="/usr/local/src/wp-plugins"

# wordpress installation
dl http://wordpress.org/latest.tar.gz $SRC

# wordpress plugins (see http://www.turnkeylinux.org/wordpress)
mkdir -p $PLUGINS_SRC
URL="http://downloads.wordpress.org/plugin"
dl $URL/wordpress-seo.latest-stable.zip $PLUGINS_SRC
dl $URL/nextgen-gallery.latest-stable.zip $PLUGINS_SRC
dl $URL/jetpack.latest-stable.zip $PLUGINS_SRC
dl $URL/google-analytics-for-wordpress.latest-stable.zip $PLUGINS_SRC
dl $URL/wp-polls.latest-stable.zip $PLUGINS_SRC
dl $URL/ozh-admin-drop-down-menu.latest-stable.zip $PLUGINS_SRC
dl $URL/wp-super-cache.latest-stable.zip $PLUGINS_SRC
dl $URL/ultimate-social-media-icons.latest-stable.zip $PLUGINS_SRC
dl $URL/simple-tags.latest-stable.zip $PLUGINS_SRC
dl $URL/backupwordpress.latest-stable.zip $PLUGINS_SRC
dl $URL/seriously-simple-podcasting.latest-stable.zip $PLUGINS_SRC
dl $URL/wp-pagenavi.latest-stable.zip $PLUGINS_SRC
dl $URL/contact-form-7.latest-stable.zip $PLUGINS_SRC

dl https://github.com/l3rady/wp-updates-notifier/archive/master.zip $PLUGINS_SRC
