#!/bin/bash -ex

WPROOT=/var/www/wordpress
NAME=wordpress
USER=www-data
DB_PREFIX=wp_
DB_PASS=$(mcookie)

ADMIN_USER=admin
ADMIN_PASS=turnkey
ADMIN_MAIL=admin@example.com

# increase php running limits
PHPINI=/etc/php/8.1/apache2/php.ini
sed -i "s|^memory_limit.*|memory_limit = 256M|" $PHPINI
sed -i "s|^upload_max_filesize.*|upload_max_filesize = 16M|" $PHPINI
sed -i "s|^post_max_size.*|post_max_size = 48M|" $PHPINI
sed -i "s|^allow_url_fopen.*|allow_url_fopen = On|" $PHPINI

# Install wp-cli commandline tool
wget https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar -O /usr/local/bin/wp
chmod +x /usr/local/bin/wp
wget https://raw.githubusercontent.com/wp-cli/wp-cli/v2.6.0/utils/wp-completion.bash -O ~/.bashrc.d/wp-completion
chmod +x ~/.bashrc.d/wp-completion

# create the database and user
service mysql start
mysqladmin create $NAME
mysql --batch --execute "grant all privileges on $NAME.* to $NAME@localhost identified by '$DB_PASS'; flush privileges;"

# install wordpress
mkdir -p $WPROOT
chown -R $USER:$USER $WPROOT
turnkey-wp core download --path=$WPROOT
cd $WPROOT
turnkey-wp config create --dbname="$NAME" \
                         --dbuser="$NAME" \
                         --dbpass="$DB_PASS" \
                         --dbprefix="$DB_PREFIX" \
                         --extra-php <<EOF
define('WP_CACHE', true);
define('DISABLE_WP_CRON', true);

// WordPress debugging mode (for developers).
define('WP_DEBUG', false);

// WordPress update method
define('FS_METHOD', 'direct');

// WordPress update policy
define('AUTOMATIC_UPDATER_DISABLED', false);
define('WP_AUTO_UPDATE_CORE', 'minor');

// Workaround wp-cli issue with unset HTTP_HOST
// For more info  see https://github.com/wp-cli/wp-cli/issues/2431 &/or
// https://make.wordpress.org/cli/handbook/common-issues/#php-notice-undefined-index-on-_server-superglobal
if ( defined( 'WP_CLI' ) && WP_CLI && ! isset( \$_SERVER['HTTP_HOST'] ) ) {
    \$_SERVER['HTTP_HOST'] = 'localhost';
}

// Single-Site (serves any hostname)
// For Multi-Site, see: https://www.turnkeylinux.org/docs/wordpress/multisite
define('WP_SITEURL', 'http://'.\$_SERVER['HTTP_HOST']);
define('WP_HOME', 'http://'.\$_SERVER['HTTP_HOST']);
EOF

# setup apache configuration and complete wordpress installation
a2dissite 000-default
a2ensite wordpress
a2enmod rewrite

# Install via custom script; wp-cli install requires URL.
cat >$WPROOT/wp-admin/turnkey-install.php<<EOF
<?php
define('WP_INSTALLING', true);
require_once('$WPROOT/wp-config.php');
require_once('$WPROOT/wp-admin/includes/upgrade.php');
//install system
wp_install("TurnKey Linux", '$ADMIN_USER', '$ADMIN_MAIL', 1);
//set admin password to something not random
\$user = get_userdatabylogin('$ADMIN_USER');
\$user = add_magic_quotes(get_object_vars(\$user));
\$user['user_pass'] = '$ADMIN_PASS';
wp_update_user(\$user);
?>
EOF

php $WPROOT/wp-admin/turnkey-install.php
rm $WPROOT/wp-admin/turnkey-install.php

# edit first post to include useful information
mysql <<EOF
USE $NAME;
UPDATE ${DB_PREFIX}posts SET post_title = 'Welcome to WordPress!' WHERE ID = '1';
UPDATE ${DB_PREFIX}posts SET post_content = 'Getting started...<ul><li><a href="/wp-login.php">Login</a> as <b>admin</b> and get blogging!</li><li>Refer to the <a href="http://www.turnkeylinux.org/wordpress">TurnKey WordPress release notes</a></li><li>Refer to the <a href="http://codex.wordpress.org/Getting_Started_with_WordPress">Wordpress Getting Started Codex</a></li><li><a href="https://wordpress.org/plugins/">Search WordPress.org for plugins</a> to extend WordPress. Here\'s some examples: <ul>
<li><a href="https://wordpress.org/plugins/wordpress-seo/">Yoast SEO</a>: Optimizes your WordPress blog for search engines and XML sitemaps.</li>
<li><a href="https://wordpress.org/plugins/nextgen-gallery/">NextGEN Gallery</a>: Easy to use image gallery with thumbnail & slideshow options.</li>
<li><a href="https://wordpress.org/plugins/jetpack/">JetPack by WordPress.com</a>: Jetpack adds powerful features previously only available to WordPress.com users including customization, traffic, mobile, content, and performance tools.</li>
<li><a href="https://wordpress.org/plugins/wp-super-cache/">WP Super Cache</a>: Accelerates your blog by serving 99% of your visitors via static HTML files.</li>
<li><a href="https://wordpress.org/plugins/ultimate-social-media-icons/">Social Media Share Buttons & Icons</a>: Promote your content by adding links to social sharing and bookmarking sites.</li>
<li><a href="https://wordpress.org/plugins/simple-tags/">Simple Tags</a>: automatically adds tags and related posts to your content.</li>
<li><a href="https://wordpress.org/plugins/backupwordpress/">BackupWordPress</a>: easily backup your core WordPress tables.</li>
<li><a href="https://wordpress.org/plugins/google-analytics-for-wordpress/">Google Analytics Dashboard for WordPress</a>: track visitors, AdSense clicks, outgoing links, and search queries.</li>
<li><a href="https://wordpress.org/plugins/wp-polls/">WP-Polls</a>: Adds an easily customizable AJAX poll system to your blog.</li>
<li><a href="https://wordpress.org/plugins/wp-pagenavi/">WP-PageNavi</a>: Adds more advanced paging navigation.</li>
<li><a href="https://wordpress.org/plugins/ozh-admin-drop-down-menu/">Ozh admin dropdown menu</a>: Creates a drop down menu with all admin links.</li>
<li><a href="https://wordpress.org/plugins/contact-form-7/">Contact Form 7</a>: Customizable contact forms supporting AJAX, CAPTCHA and Akismet integration.</li>
<li><a href="https://wordpress.org/plugins/seriously-simple-podcasting/">Seriously Simple Podcasting</a>: Simple Podcasting from your WordPress site.</li>
</ul></li></ul>' WHERE ID = '1';
EOF

# fix permissions for updates
chown -R www-data:www-data $WPROOT
find $WPROOT -type d -exec chmod 755 {} \;
find $WPROOT -type f -exec chmod 644 {} \;

# stop mysql server
service mysql stop
