#!/bin/bash -e
# regenerate wordpress secrets and mysql password

. /etc/default/inithooks

USER=www-data
WEBROOT=/var/www/wordpress
CONF=$WEBROOT/wp-config.php

updateconf() {
    sed -i "\|^define(.*'$1'|s|,.*|, '$2');|" $CONF
}

runuser $USER -s /bin/bash -c "wp --path=$WEBROOT config shuffle-salts"

PASSWORD=$(mcookie)
updateconf DB_PASSWORD "$PASSWORD"
$INITHOOKS_PATH/bin/mysqlconf.py --user=wordpress --pass="$PASSWORD"
