#!/bin/bash -e
# regenerate wordpress secrets and mysql password

. /etc/default/inithooks

updateconf() {
    CONF=/var/www/wordpress/wp-config.php
    sed -i "/^define('$1'/ s|,.*|, '$2');|" $CONF
}

updateconf AUTH_KEY $(mcookie)$(mcookie)
updateconf AUTH_SALT $(mcookie)$(mcookie)
updateconf SECURE_AUTH_KEY $(mcookie)$(mcookie)
updateconf SECURE_AUTH_SALT $(mcookie)$(mcookie)
updateconf LOGGED_IN_KEY $(mcookie)$(mcookie)
updateconf LOGGED_IN_SALT $(mcookie)$(mcookie)
updateconf NONCE_KEY $(mcookie)$(mcookie)
updateconf NONCE_SALT $(mcookie)$(mcookie)

PASSWORD=$(mcookie)
updateconf DB_PASSWORD $PASSWORD
$INITHOOKS_PATH/bin/mysqlconf.py --user=wordpress --pass="$PASSWORD"
