#!/bin/bash -e
# set wordpress admin password and email

. /etc/default/inithooks

# shellcheck source=/dev/null
[[ -e $INITHOOKS_CONF ]] && . $INITHOOKS_CONF

$INITHOOKS_PATH/bin/wordpress.py --pass="$APP_PASS" --email="$APP_EMAIL" \
                --domain="$APP_DOMAIN"
