#!/bin/bash -e
# set wordpress admin password and email

. /etc/default/inithooks

[[ -e $INITHOOKS_CONF ]] && . $INITHOOKS_CONF

# if APP_PASS & APP_EMAIL set, assume preseeded
if [[ -n "$APP_PASS" ]] && [[ -n "$APP_EMAIL" ]]; then
    APP_DOMAIN=${APP_DOMAIN:-NONE}
fi

$INITHOOKS_PATH/bin/wordpress.py --pass="$APP_PASS" --email="$APP_EMAIL" \
                --domain="$APP_DOMAIN"
